# -*- coding: utf-8 -*-
"""newocrtest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TUQH4rJW63i9_BkWZepUNxPEUFCm0A-K
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

cnn = tf.keras.models.load_model("/content/train_model.h5")

import cv2
image_path = "/content/drive/MyDrive/newocr dataset/testing_data/A/28392.png"
img = cv2.imread(image_path)
plt.imshow(img)
plt.title("Test image")
plt.xticks([])
plt.yticks([])
plt.show()

image = tf.keras.preprocessing.image.load_img(image_path, target_size=(64,64))
input_arr = tf.keras.preprocessing.image.img_to_array(image)
input_arr = np.array([input_arr]) #converting single image to batch
predictions = cnn.predict(input_arr)

print(predictions[0])
print(max(predictions[0]))

test_set = tf.keras.utils.image_dataset_from_directory(
    '/content/drive/MyDrive/newocr dataset/testing_data',
    labels = "inferred",
    label_mode = "categorical" ,
    class_names = None,
    color_mode = "rgb" ,
    batch_size = 32,
    image_size = (64,64),
    shuffle = True,
    seed = None,
    validation_split = None,
    subset = None,
    interpolation = "bilinear",
    follow_links = False,
    crop_to_aspect_ratio = False
)

test_set.class_names

file = open("label.txt", "w")#just creating our class names in the form of txt in notepad
for i in test_set.class_names:
  file.write(i+'\n')
file.close()

with open("label.txt") as f:
  content = f.readlines()

content

result_index = np.where(predictions[0] == max(predictions[0]))
print(result_index)

plt.imshow(img)
plt.title("Test image")
plt.xticks([])
plt.yticks([])
plt.show()

print("Its a {}" .format(test_set.class_names[result_index[0][0]]))

